version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=db_name
      - JWT_SECRET=your-secret-key
      - PORT=8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db

volumes:
  mongodb_data: 